name: "Build and Test"

on:
    workflow_call:
        inputs:
            testOnMacOS:
                required: false
                description: "Whether the package should be compiled and tested on MacOS"
                type: "boolean"
                default: true
            testOnLinux:
                required: false
                description: "Whether the package should be compiled and tested on Linux"
                type: "boolean"
                default: true
            testOnWindows:
                required: false
                description: "Whether the package should be compiled and tested on Windows"
                type: "boolean"
                default: true
            testCommandMacOS:
                required: false
                description: "Command to run to test the Swift package on macOS"
                type: "string"
                default: "swift test"
            testCommandLinux:
                required: false
                description: "Command to run to test the Swift package on Linux"
                type: "string"
                default: "swift test"
            testCommandWindows:
                required: false
                description: "Command to run to test the Swift package on Windows"
                type: "string"
                default: "swift test -Xcc -D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH -Xcxx -D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH"

jobs:
    TestOnMacOS-Latest:
        if: ${{ inputs.testOnMacOS }}
        runs-on: "macos-latest"
        steps:
            - uses: "actions/checkout@v4"
            - name: "Run tests"
              run: "${{ inputs.testCommandMacOS }}"
    # TestOnUbuntu-20_04-ARM:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/checkout@v2
    #     - uses: uraimo/run-on-arch-action@v2.0.7
    #       with:
    #         arch: aarch64
    #         distro: ubuntu20.04
    #         githubToken: ${{ secrets.GITHUB_TOKEN }}
    #         run: |
    #           export DEBIAN_FRONTEND=noninteractive
    #           apt update -q
    #           apt install -yq curl sudo
    #           curl -s https://packagecloud.io/install/repositories/swift-arm/release/script.deb.sh | sudo bash
    #           apt install -yq swiftlang
    #           apt update -yq
    #           swift test
    TestOnUbuntu-20_04-x86_64:
        if: ${{ inputs.testOnLinux }}
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v4"
            - name: "Run tests"
              run: "${{ inputs.testCommandLinux }}"
    TestOnWindows10-x86_64:
        if: ${{ inputs.testOnWindows }}
        runs-on: "windows-latest"
        steps:
            - uses: "actions/checkout@v4"
            - uses: "seanmiddleditch/gha-setup-vsdevenv@master"
            - uses: "compnerd/gha-setup-swift@main"
              with:
                  branch: "swift-6.0-release"
                  tag: "6.0-RELEASE"
            - name: "Test"
              run: "${{ inputs.testCommandWindows }}"
